// THIS FILE IS AUTOMATICALLY GENERATED FROM THE GGF SCHEMA
// Generated on: 2025-11-02T23:28:33.275Z
// Source: /src/lib/data/schema/_index.ts
// Generator: scripts/generate-nav.js
//
// DO NOT EDIT THIS FILE MANUALLY - IT WILL BE OVERWRITTEN
// To modify framework data, edit the schema files in /src/lib/data/schema/

import { writable } from 'svelte/store';

// Helper function to convert kebab-case slug to camelCase translation key
function slugToTitleKey(slug) {
  return slug
    .split('-')
    .map((word, index) => 
      index === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1)
    )
    .join('');
}

// Master list of all frameworks - GENERATED FROM SCHEMA
export const allFrameworks = [
  {
    "slug": "treaty-for-our-only-home",
    "titleKey": "framework.docs.nav.frameworkTitles.treatyForOurOnlyHome",
    "emoji": "🌐",
    "tier": 0,
    "status": "ready",
    "version": "1.1",
    "path": "/frameworks/treaty-for-our-only-home"
  },
  {
    "slug": "institutional-regeneration",
    "titleKey": "framework.docs.nav.frameworkTitles.institutionalRegeneration",
    "emoji": "🔄",
    "tier": 1,
    "status": "ready",
    "version": "0.8",
    "path": "/frameworks/institutional-regeneration"
  },
  {
    "slug": "pathfinder-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.pathfinderProtocol",
    "emoji": "🧭",
    "tier": 2,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/pathfinder-protocol",
    "group": "globalEconomicSystems"
  },
  {
    "slug": "aegis-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.aegisProtocol",
    "emoji": "🛰️",
    "tier": 1,
    "status": "ready",
    "version": "0.9",
    "path": "/frameworks/aegis-protocol",
    "group": "socialFabricJustice"
  },
  {
    "slug": "sundown-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.sundownProtocol",
    "emoji": "🌇",
    "tier": 2,
    "status": "planned",
    "version": "1.0",
    "path": "/frameworks/sundown-protocol"
  },
  {
    "slug": "meta-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.metaGovernance",
    "emoji": "🏛️",
    "tier": 1,
    "status": "ready",
    "version": "1.1",
    "path": "/frameworks/meta-governance"
  },
  {
    "slug": "emergent-governance-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.emergentGovernanceProtocol",
    "emoji": "🗣️",
    "tier": 1,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/emergent-governance-protocol"
  },
  {
    "slug": "implementation-and-adaptation",
    "titleKey": "framework.docs.nav.frameworkTitles.implementationAndAdaptation",
    "emoji": "🧰",
    "tier": 1,
    "status": "planned",
    "version": "1.0",
    "path": "/frameworks/implementation-and-adaptation"
  },
  {
    "slug": "indigenous-governance-and-traditional-knowledge",
    "titleKey": "framework.docs.nav.frameworkTitles.indigenousGovernanceAndTraditionalKnowledge",
    "emoji": "🪶",
    "tier": 1,
    "status": "review",
    "version": "0.9",
    "path": "/frameworks/indigenous-governance-and-traditional-knowledge",
    "group": "socialFabricJustice"
  },
  {
    "slug": "moral-operating-system",
    "titleKey": "framework.docs.nav.frameworkTitles.moralOperatingSystem",
    "emoji": "🦋",
    "tier": 1,
    "status": "review",
    "path": "/frameworks/moral-operating-system"
  },
  {
    "slug": "peace-and-conflict-resolution",
    "titleKey": "framework.docs.nav.frameworkTitles.peaceAndConflictResolution",
    "emoji": "🕊️",
    "tier": 1,
    "status": "review",
    "path": "/frameworks/peace-and-conflict-resolution",
    "group": "socialFabricJustice"
  },
  {
    "slug": "justice-systems",
    "titleKey": "framework.docs.nav.frameworkTitles.justiceSystems",
    "emoji": "⚖️",
    "tier": 1,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/justice-systems",
    "group": "socialFabricJustice"
  },
  {
    "slug": "shield-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.shieldProtocol",
    "emoji": "🛡️",
    "tier": 1,
    "status": "planned",
    "path": "/frameworks/shield-protocol",
    "group": "socialFabricJustice"
  },
  {
    "slug": "adaptive-universal-basic-income",
    "titleKey": "framework.docs.nav.frameworkTitles.adaptiveUniversalBasicIncome",
    "emoji": "💰",
    "tier": 1,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/adaptive-universal-basic-income",
    "group": "globalEconomicSystems"
  },
  {
    "slug": "financial-systems",
    "titleKey": "framework.docs.nav.frameworkTitles.financialSystems",
    "emoji": "❤️",
    "tier": 1,
    "status": "review",
    "path": "/frameworks/financial-systems",
    "group": "globalEconomicSystems"
  },
  {
    "slug": "work-in-liberation",
    "titleKey": "framework.docs.nav.frameworkTitles.workInLiberation",
    "emoji": "👥",
    "tier": 1,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/work-in-liberation",
    "group": "globalEconomicSystems"
  },
  {
    "slug": "nested-economies",
    "titleKey": "framework.docs.nav.frameworkTitles.nestedEconomies",
    "emoji": "💱",
    "tier": 1,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/nested-economies",
    "group": "globalEconomicSystems"
  },
  {
    "slug": "gaian-trade",
    "titleKey": "framework.docs.nav.frameworkTitles.gaianTrade",
    "emoji": "🌍",
    "tier": 1,
    "status": "review",
    "path": "/frameworks/gaian-trade",
    "group": "globalEconomicSystems"
  },
  {
    "slug": "global-supply-chains-and-logistics",
    "titleKey": "framework.docs.nav.frameworkTitles.globalSupplyChainsAndLogistics",
    "emoji": "🚢",
    "tier": 1,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/global-supply-chains-and-logistics",
    "group": "globalEconomicSystems"
  },
  {
    "slug": "aurora-accord",
    "titleKey": "framework.docs.nav.frameworkTitles.auroraAccord",
    "emoji": "📜",
    "tier": 1,
    "status": "review",
    "path": "/frameworks/aurora-accord",
    "group": "globalEconomicSystems"
  },
  {
    "slug": "technology-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.technologyGovernance",
    "emoji": "🤖",
    "tier": 1,
    "status": "ready",
    "version": "3.2",
    "path": "/frameworks/technology-governance",
    "group": "humanSocialSystems"
  },
  {
    "slug": "aethelred-accord",
    "titleKey": "framework.docs.nav.frameworkTitles.aethelredAccord",
    "emoji": "🧬",
    "tier": 2,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/aethelred-accord",
    "group": "humanSocialSystems"
  },
  {
    "slug": "planetary-health-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.planetaryHealthGovernance",
    "emoji": "💚",
    "tier": 2,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/planetary-health-governance",
    "group": "planetaryHealthResilience"
  },
  {
    "slug": "environmental-stewardship",
    "titleKey": "framework.docs.nav.frameworkTitles.environmentalStewardship",
    "emoji": "🌿",
    "tier": 2,
    "status": "review",
    "path": "/frameworks/environmental-stewardship",
    "group": "ecologicalSystems"
  },
  {
    "slug": "climate-and-energy-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.climateAndEnergyGovernance",
    "emoji": "⚡",
    "tier": 2,
    "status": "review",
    "path": "/frameworks/climate-and-energy-governance",
    "group": "planetaryHealthResilience"
  },
  {
    "slug": "kinship-garden",
    "titleKey": "framework.docs.nav.frameworkTitles.kinshipGarden",
    "emoji": "🌱",
    "tier": 2,
    "status": "review",
    "path": "/frameworks/kinship-garden",
    "group": "planetaryHealthResilience"
  },
  {
    "slug": "soil-health-and-land-use-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.soilHealthAndLandUseGovernance",
    "emoji": "🌾",
    "tier": 2,
    "status": "planned",
    "path": "/frameworks/soil-health-and-land-use-governance",
    "group": "ecologicalSystems"
  },
  {
    "slug": "water-and-sanitation-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.waterAndSanitationGovernance",
    "emoji": "💧",
    "tier": 2,
    "status": "review",
    "path": "/frameworks/water-and-sanitation-governance",
    "group": "ecologicalSystems"
  },
  {
    "slug": "biodiversity-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.biodiversityGovernance",
    "emoji": "🦅",
    "tier": 2,
    "status": "review",
    "path": "/frameworks/biodiversity-governance",
    "group": "ecologicalSystems"
  },
  {
    "slug": "oceans-and-marine-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.oceansAndMarineGovernance",
    "emoji": "🌊",
    "tier": 2,
    "status": "planned",
    "path": "/frameworks/oceans-and-marine-governance",
    "group": "ecologicalSystems"
  },
  {
    "slug": "animal-welfare-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.animalWelfareGovernance",
    "emoji": "🐾",
    "tier": 2,
    "status": "review",
    "path": "/frameworks/animal-welfare-governance",
    "group": "ecologicalSystems"
  },
  {
    "slug": "phoenix-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.phoenixProtocol",
    "emoji": "♻️",
    "tier": 2,
    "status": "planned",
    "path": "/frameworks/phoenix-protocol",
    "group": "ecologicalSystems"
  },
  {
    "slug": "disaster-risk-reduction",
    "titleKey": "framework.docs.nav.frameworkTitles.disasterRiskReduction",
    "emoji": "🌪️",
    "tier": 2,
    "status": "review",
    "path": "/frameworks/disaster-risk-reduction",
    "group": "planetaryHealthResilience"
  },
  {
    "slug": "educational-systems",
    "titleKey": "framework.docs.nav.frameworkTitles.educationalSystems",
    "emoji": "🎓",
    "tier": 2,
    "status": "review",
    "path": "/frameworks/educational-systems",
    "group": "humanSocialSystems"
  },
  {
    "slug": "global-health-and-pandemic-security",
    "titleKey": "framework.docs.nav.frameworkTitles.globalHealthAndPandemicSecurity",
    "emoji": "⚕️",
    "tier": 2,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/global-health-and-pandemic-security",
    "group": "planetaryHealthResilience"
  },
  {
    "slug": "mental-health-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.mentalHealthGovernance",
    "emoji": "🧠",
    "tier": 2,
    "status": "review",
    "path": "/frameworks/mental-health-governance",
    "group": "humanSocialSystems"
  },
  {
    "slug": "sanctuary-accord",
    "titleKey": "framework.docs.nav.frameworkTitles.sanctuaryAccord",
    "emoji": "🍄",
    "tier": 2,
    "status": "draft",
    "version": "1.6",
    "path": "/frameworks/sanctuary-accord",
    "group": "humanSocialSystems"
  },
  {
    "slug": "synoptic-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.synopticProtocol",
    "emoji": "👁️",
    "tier": 2,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/synoptic-protocol",
    "group": "humanSocialSystems"
  },
  {
    "slug": "prometheus-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.prometheusProtocol",
    "emoji": "⚕️",
    "tier": 2,
    "status": "planned",
    "version": "7.1",
    "path": "/frameworks/prometheus-protocol",
    "group": "planetaryHealthResilience"
  },
  {
    "slug": "discovery-commons",
    "titleKey": "framework.docs.nav.frameworkTitles.discoveryCommons",
    "emoji": "🔬",
    "tier": 2,
    "status": "planned",
    "version": "1.0",
    "path": "/frameworks/discovery-commons"
  },
  {
    "slug": "kintsugi-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.kintsugiProtocol",
    "emoji": "🏺",
    "tier": 2,
    "status": "planned",
    "version": "2.0",
    "path": "/frameworks/kintsugi-protocol",
    "group": "humanSocialSystems"
  },
  {
    "slug": "social-fabric",
    "titleKey": "framework.docs.nav.frameworkTitles.socialFabric",
    "emoji": "🧶",
    "tier": 2,
    "status": "planned",
    "version": "1.0",
    "path": "/frameworks/social-fabric",
    "group": "humanSocialSystems"
  },
  {
    "slug": "cairn-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.cairnProtocol",
    "emoji": "🗿",
    "tier": 2,
    "status": "planned",
    "version": "2.3",
    "path": "/frameworks/cairn-protocol",
    "group": "socialFabricJustice"
  },
  {
    "slug": "disability-rights-and-inclusion",
    "titleKey": "framework.docs.nav.frameworkTitles.disabilityRightsAndInclusion",
    "emoji": "♿",
    "tier": 3,
    "status": "coming-soon",
    "path": "/frameworks/disability-rights-and-inclusion",
    "group": "humanSocialSystems"
  },
  {
    "slug": "kinship-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.kinshipProtocol",
    "emoji": "🫂",
    "tier": 3,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/kinship-protocol"
  },
  {
    "slug": "youth-and-intergenerational-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.youthAndIntergenerationalGovernance",
    "emoji": "👶",
    "tier": 3,
    "status": "planned",
    "path": "/frameworks/youth-and-intergenerational-governance"
  },
  {
    "slug": "aging-population-support-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.agingPopulationSupportGovernance",
    "emoji": "🌳",
    "tier": 3,
    "status": "review",
    "path": "/frameworks/aging-population-support-governance"
  },
  {
    "slug": "migration-and-human-mobility",
    "titleKey": "framework.docs.nav.frameworkTitles.migrationAndHumanMobility",
    "emoji": "🗺️",
    "tier": 3,
    "status": "review",
    "path": "/frameworks/migration-and-human-mobility",
    "group": "socialFabricJustice"
  },
  {
    "slug": "cultural-heritage-preservation",
    "titleKey": "framework.docs.nav.frameworkTitles.culturalHeritagePreservation",
    "emoji": "🏛️",
    "tier": 3,
    "status": "planned",
    "path": "/frameworks/cultural-heritage-preservation"
  },
  {
    "slug": "digital-commons",
    "titleKey": "framework.docs.nav.frameworkTitles.digitalCommons",
    "emoji": "💻",
    "tier": 3,
    "status": "review",
    "path": "/frameworks/digital-commons"
  },
  {
    "slug": "religious-and-spiritual-dialogue-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.religiousAndSpiritualDialogueGovernance",
    "emoji": "🕯️",
    "tier": 3,
    "status": "review",
    "path": "/frameworks/religious-and-spiritual-dialogue-governance"
  },
  {
    "slug": "global-citizenship-practice",
    "titleKey": "framework.docs.nav.frameworkTitles.globalCitizenshipPractice",
    "emoji": "🤝",
    "tier": 3,
    "status": "review",
    "path": "/frameworks/global-citizenship-practice"
  },
  {
    "slug": "arts-flourishing",
    "titleKey": "framework.docs.nav.frameworkTitles.artsFlourishing",
    "emoji": "🎨",
    "tier": 3,
    "status": "planned",
    "path": "/frameworks/arts-flourishing",
    "group": "humanSocialSystems"
  },
  {
    "slug": "consciousness-and-inner-development",
    "titleKey": "framework.docs.nav.frameworkTitles.consciousnessAndInnerDevelopment",
    "emoji": "🧘",
    "tier": 4,
    "status": "review",
    "path": "/frameworks/consciousness-and-inner-development"
  },
  {
    "slug": "wise-decision-making-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.wiseDecisionMakingProtocol",
    "emoji": "🧭",
    "tier": 4,
    "status": "review",
    "path": "/frameworks/wise-decision-making-protocol"
  },
  {
    "slug": "mobility-commons",
    "titleKey": "framework.docs.nav.frameworkTitles.mobilityCommons",
    "emoji": "🚆",
    "tier": 2,
    "status": "draft",
    "path": "/frameworks/mobility-commons",
    "group": "planetaryHealthResilience"
  },
  {
    "slug": "bioregional-polis",
    "titleKey": "framework.docs.nav.frameworkTitles.bioregionalPolis",
    "emoji": "🏙️",
    "tier": 3,
    "status": "coming-soon",
    "path": "/frameworks/bioregional-polis",
    "group": "humanSocialSystems"
  },
  {
    "slug": "living-land-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.livingLandProtocol",
    "emoji": "🛖",
    "tier": 3,
    "status": "planned",
    "path": "/frameworks/living-land-protocol"
  },
  {
    "slug": "regenerative-journeys",
    "titleKey": "framework.docs.nav.frameworkTitles.regenerativeJourneys",
    "emoji": "👣",
    "tier": 3,
    "status": "ready",
    "path": "/frameworks/regenerative-journeys",
    "group": "humanSocialSystems"
  },
  {
    "slug": "existential-risk-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.existentialRiskGovernance",
    "emoji": "⚠️",
    "tier": 4,
    "status": "planned",
    "path": "/frameworks/existential-risk-governance"
  },
  {
    "slug": "space-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.spaceGovernance",
    "emoji": "🚀",
    "tier": 4,
    "status": "planned",
    "path": "/frameworks/space-governance"
  },
  {
    "slug": "millennium-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.millenniumProtocol",
    "emoji": "🌌",
    "tier": 4,
    "status": "planned",
    "version": "6.0",
    "path": "/frameworks/millennium-protocol"
  },
  {
    "slug": "deep-time-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.deepTimeGovernance",
    "emoji": "⏳",
    "tier": 4,
    "status": "planned",
    "path": "/frameworks/deep-time-governance"
  },
  {
    "slug": "wisdom-governance",
    "titleKey": "framework.docs.nav.frameworkTitles.wisdomGovernance",
    "emoji": "🦉",
    "tier": 4,
    "status": "planned",
    "path": "/frameworks/wisdom-governance"
  },
  {
    "slug": "oracle-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.oracleProtocol",
    "emoji": "🔮",
    "tier": 4,
    "status": "planned",
    "version": "2.7",
    "path": "/frameworks/oracle-protocol"
  },
  {
    "slug": "hearthstone-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.hearthstoneProtocol",
    "emoji": "🔥",
    "tier": 2,
    "status": "ready",
    "version": "1.5",
    "path": "/frameworks/hearthstone-protocol"
  },
  {
    "slug": "conduit-protocol",
    "titleKey": "framework.docs.nav.frameworkTitles.conduitProtocol",
    "emoji": "🔌",
    "tier": 2,
    "status": "ready",
    "version": "1.0",
    "path": "/frameworks/conduit-protocol"
  }
];

// Group metadata for i18n - GENERATED FROM SCHEMA
export const groupMetadata = {
  "planetaryHealthResilience": {
    "titleKey": "framework.groups.planetaryHealthResilience.title",
    "descriptionKey": "framework.groups.planetaryHealthResilience.description",
    "emoji": "🌱"
  },
  "socialFabricJustice": {
    "titleKey": "framework.groups.socialFabricJustice.title",
    "descriptionKey": "framework.groups.socialFabricJustice.description",
    "emoji": "⚖️"
  },
  "globalEconomicSystems": {
    "titleKey": "framework.groups.globalEconomicSystems.title",
    "descriptionKey": "framework.groups.globalEconomicSystems.description",
    "emoji": "💱"
  },
  "ecologicalSystems": {
    "titleKey": "framework.groups.ecologicalSystems.title",
    "descriptionKey": "framework.groups.ecologicalSystems.description",
    "emoji": "🌿"
  },
  "humanSocialSystems": {
    "titleKey": "framework.groups.humanSocialSystems.title",
    "descriptionKey": "framework.groups.humanSocialSystems.description",
    "emoji": "🎓"
  }
};

// Tier metadata - GENERATED FROM SCHEMA (with translation keys)
export const tierMetadata = {
  "0": {
    "name": "Constitutional Layer",
    "titleKey": "framework.tier.0.title",
    "descriptionKey": "framework.tier.0.description",
    "emoji": "⚖️",
    "description": "The absolute, non-negotiable prerequisite. The new global \"constitution\" that makes everything else legally and institutionally possible.",
    "color": "#1e1b4b",
    "priority": "Critical",
    "keyCharacteristics": [
      "Legal foundation",
      "Institutional reform",
      "Enforcement mechanisms"
    ]
  },
  "1": {
    "name": "Core Operating Systems",
    "titleKey": "framework.tier.1.title",
    "descriptionKey": "framework.tier.1.description",
    "emoji": "🌍",
    "description": "Foundational frameworks that define the GGF's core governance, economic, ethical, and justice systems.",
    "color": "#7c3aed",
    "priority": "Critical",
    "keyCharacteristics": [
      "Governance coordination",
      "Economic engine",
      "Justice foundation",
      "Ethical compass"
    ]
  },
  "2": {
    "name": "Foundational Application Layer",
    "titleKey": "framework.tier.2.title",
    "descriptionKey": "framework.tier.2.description",
    "emoji": "🌱",
    "description": "Essential frameworks for managing core societal and ecological systems.",
    "color": "#059669",
    "priority": "High",
    "keyCharacteristics": [
      "Life support systems",
      "Human capabilities",
      "Ecological integrity"
    ]
  },
  "3": {
    "name": "Equity & Cultural Flourishing Layer",
    "titleKey": "framework.tier.3.title",
    "descriptionKey": "framework.tier.3.description",
    "emoji": "🤝",
    "description": "Frameworks ensuring deep equity, inclusion, and cultural preservation.",
    "color": "#dc2626",
    "priority": "Medium",
    "keyCharacteristics": [
      "Social equity",
      "Cultural preservation",
      "Knowledge commons"
    ]
  },
  "4": {
    "name": "Visionary & Meta-Governance Layer",
    "titleKey": "framework.tier.4.title",
    "descriptionKey": "framework.tier.4.description",
    "emoji": "🔮",
    "description": "Highest level frameworks governing the entire system and addressing future risks.",
    "color": "#0891b2",
    "priority": "Medium",
    "keyCharacteristics": [
      "System governance",
      "Future orientation",
      "Existential risk",
      "Consciousness evolution"
    ]
  }
};

// Status mapping - GENERATED FROM SCHEMA
export const statusMapping = {
  "ready": "framework.status.ready.label",
  "review": "framework.status.review.label",
  "planned": "framework.labels.planned",
  "coming-soon": "framework.labels.comingSoon"
};

// Helper functions (preserved from original)
export function getFrameworksByTier(tier) {
  return allFrameworks.filter(framework => framework.tier === tier);
}

export function getFrameworksByTierAndGroup(tier, group = null) {
  const tierFrameworks = getFrameworksByTier(tier);
  if (group) {
    return tierFrameworks.filter(framework => framework.group === group);
  }
  return tierFrameworks.filter(framework => !framework.group); // Ungrouped frameworks
}

export function getGroupsForTier(tier) {
  const tierFrameworks = getFrameworksByTier(tier);
  const groups = [...new Set(tierFrameworks.map(f => f.group).filter(Boolean))];
  return groups;
}

export function getFrameworkBySlug(slug) {
  return allFrameworks.find(framework => framework.slug === slug);
}

export function getAllTiers() {
  return [...new Set(allFrameworks.map(f => f.tier))].sort();
}

// Function to dynamically generate titleKey from slug (useful for validation)
export function generateTitleKeyFromSlug(slug) {
  const camelCase = slugToTitleKey(slug);
  return `framework.docs.nav.frameworkTitles.${camelCase}`;
}

// Build navigation structure from the master list (for backwards compatibility)
function buildNavStructure(frameworks) {
  const navStructure = [
  {
    "titleKey": "framework.docs.nav.overview",
    "path": "/frameworks"
  },
  {
    "titleKey": "framework.docs.nav.documentation",
    "path": "/frameworks/docs"
  },
  {
    "titleKey": "framework.docs.nav.principles",
    "path": "/frameworks/docs/principles"
  },
  {
    "titleKey": "framework.docs.nav.implementation",
    "path": "/frameworks",
    "status": "ready",
    "subItems": [
      {
        "titleKey": "framework.tier.0.title",
        "path": "/frameworks/tier-0",
        "subItems": [
          {
            "titleKey": "framework.docs.nav.frameworkTitles.treatyForOurOnlyHome",
            "path": "/frameworks/treaty-for-our-only-home",
            "status": "ready",
            "version": "1.1",
            "emoji": "🌐"
          }
        ]
      },
      {
        "titleKey": "framework.tier.1.title",
        "path": "/frameworks/tier-1",
        "subItems": [
          {
            "titleKey": "framework.docs.nav.frameworkTitles.institutionalRegeneration",
            "path": "/frameworks/institutional-regeneration",
            "status": "ready",
            "version": "0.8",
            "emoji": "🔄"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.aegisProtocol",
            "path": "/frameworks/aegis-protocol",
            "status": "ready",
            "version": "0.9",
            "emoji": "🛰️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.metaGovernance",
            "path": "/frameworks/meta-governance",
            "status": "ready",
            "version": "1.1",
            "emoji": "🏛️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.emergentGovernanceProtocol",
            "path": "/frameworks/emergent-governance-protocol",
            "status": "ready",
            "version": "1.0",
            "emoji": "🗣️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.implementationAndAdaptation",
            "path": "/frameworks/implementation-and-adaptation",
            "status": "planned",
            "version": "1.0",
            "emoji": "🧰"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.indigenousGovernanceAndTraditionalKnowledge",
            "path": "/frameworks/indigenous-governance-and-traditional-knowledge",
            "status": "review",
            "version": "0.9",
            "emoji": "🪶"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.moralOperatingSystem",
            "path": "/frameworks/moral-operating-system",
            "status": "review",
            "emoji": "🦋"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.peaceAndConflictResolution",
            "path": "/frameworks/peace-and-conflict-resolution",
            "status": "review",
            "emoji": "🕊️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.justiceSystems",
            "path": "/frameworks/justice-systems",
            "status": "ready",
            "version": "1.0",
            "emoji": "⚖️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.shieldProtocol",
            "path": "/frameworks/shield-protocol",
            "status": "planned",
            "emoji": "🛡️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.adaptiveUniversalBasicIncome",
            "path": "/frameworks/adaptive-universal-basic-income",
            "status": "ready",
            "version": "1.0",
            "emoji": "💰"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.financialSystems",
            "path": "/frameworks/financial-systems",
            "status": "review",
            "emoji": "❤️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.workInLiberation",
            "path": "/frameworks/work-in-liberation",
            "status": "ready",
            "version": "1.0",
            "emoji": "👥"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.nestedEconomies",
            "path": "/frameworks/nested-economies",
            "status": "ready",
            "version": "1.0",
            "emoji": "💱"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.gaianTrade",
            "path": "/frameworks/gaian-trade",
            "status": "review",
            "emoji": "🌍"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.globalSupplyChainsAndLogistics",
            "path": "/frameworks/global-supply-chains-and-logistics",
            "status": "ready",
            "version": "1.0",
            "emoji": "🚢"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.auroraAccord",
            "path": "/frameworks/aurora-accord",
            "status": "review",
            "emoji": "📜"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.technologyGovernance",
            "path": "/frameworks/technology-governance",
            "status": "ready",
            "version": "3.2",
            "emoji": "🤖"
          }
        ]
      },
      {
        "titleKey": "framework.tier.2.title",
        "path": "/frameworks/tier-2",
        "subItems": [
          {
            "titleKey": "framework.docs.nav.frameworkTitles.pathfinderProtocol",
            "path": "/frameworks/pathfinder-protocol",
            "status": "ready",
            "version": "1.0",
            "emoji": "🧭"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.sundownProtocol",
            "path": "/frameworks/sundown-protocol",
            "status": "planned",
            "version": "1.0",
            "emoji": "🌇"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.aethelredAccord",
            "path": "/frameworks/aethelred-accord",
            "status": "ready",
            "version": "1.0",
            "emoji": "🧬"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.planetaryHealthGovernance",
            "path": "/frameworks/planetary-health-governance",
            "status": "ready",
            "version": "1.0",
            "emoji": "💚"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.environmentalStewardship",
            "path": "/frameworks/environmental-stewardship",
            "status": "review",
            "emoji": "🌿"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.climateAndEnergyGovernance",
            "path": "/frameworks/climate-and-energy-governance",
            "status": "review",
            "emoji": "⚡"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.kinshipGarden",
            "path": "/frameworks/kinship-garden",
            "status": "review",
            "emoji": "🌱"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.soilHealthAndLandUseGovernance",
            "path": "/frameworks/soil-health-and-land-use-governance",
            "status": "planned",
            "emoji": "🌾"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.waterAndSanitationGovernance",
            "path": "/frameworks/water-and-sanitation-governance",
            "status": "review",
            "emoji": "💧"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.biodiversityGovernance",
            "path": "/frameworks/biodiversity-governance",
            "status": "review",
            "emoji": "🦅"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.oceansAndMarineGovernance",
            "path": "/frameworks/oceans-and-marine-governance",
            "status": "planned",
            "emoji": "🌊"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.animalWelfareGovernance",
            "path": "/frameworks/animal-welfare-governance",
            "status": "review",
            "emoji": "🐾"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.phoenixProtocol",
            "path": "/frameworks/phoenix-protocol",
            "status": "planned",
            "emoji": "♻️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.disasterRiskReduction",
            "path": "/frameworks/disaster-risk-reduction",
            "status": "review",
            "emoji": "🌪️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.educationalSystems",
            "path": "/frameworks/educational-systems",
            "status": "review",
            "emoji": "🎓"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.globalHealthAndPandemicSecurity",
            "path": "/frameworks/global-health-and-pandemic-security",
            "status": "ready",
            "version": "1.0",
            "emoji": "⚕️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.mentalHealthGovernance",
            "path": "/frameworks/mental-health-governance",
            "status": "review",
            "emoji": "🧠"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.sanctuaryAccord",
            "path": "/frameworks/sanctuary-accord",
            "status": "draft",
            "version": "1.6",
            "emoji": "🍄"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.synopticProtocol",
            "path": "/frameworks/synoptic-protocol",
            "status": "ready",
            "version": "1.0",
            "emoji": "👁️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.prometheusProtocol",
            "path": "/frameworks/prometheus-protocol",
            "status": "planned",
            "version": "7.1",
            "emoji": "⚕️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.discoveryCommons",
            "path": "/frameworks/discovery-commons",
            "status": "planned",
            "version": "1.0",
            "emoji": "🔬"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.kintsugiProtocol",
            "path": "/frameworks/kintsugi-protocol",
            "status": "planned",
            "version": "2.0",
            "emoji": "🏺"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.socialFabric",
            "path": "/frameworks/social-fabric",
            "status": "planned",
            "version": "1.0",
            "emoji": "🧶"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.cairnProtocol",
            "path": "/frameworks/cairn-protocol",
            "status": "planned",
            "version": "2.3",
            "emoji": "🗿"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.mobilityCommons",
            "path": "/frameworks/mobility-commons",
            "status": "draft",
            "emoji": "🚆"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.hearthstoneProtocol",
            "path": "/frameworks/hearthstone-protocol",
            "status": "ready",
            "version": "1.5",
            "emoji": "🔥"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.conduitProtocol",
            "path": "/frameworks/conduit-protocol",
            "status": "ready",
            "version": "1.0",
            "emoji": "🔌"
          }
        ]
      },
      {
        "titleKey": "framework.tier.3.title",
        "path": "/frameworks/tier-3",
        "subItems": [
          {
            "titleKey": "framework.docs.nav.frameworkTitles.disabilityRightsAndInclusion",
            "path": "/frameworks/disability-rights-and-inclusion",
            "status": "coming-soon",
            "emoji": "♿"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.kinshipProtocol",
            "path": "/frameworks/kinship-protocol",
            "status": "ready",
            "version": "1.0",
            "emoji": "🫂"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.youthAndIntergenerationalGovernance",
            "path": "/frameworks/youth-and-intergenerational-governance",
            "status": "planned",
            "emoji": "👶"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.agingPopulationSupportGovernance",
            "path": "/frameworks/aging-population-support-governance",
            "status": "review",
            "emoji": "🌳"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.migrationAndHumanMobility",
            "path": "/frameworks/migration-and-human-mobility",
            "status": "review",
            "emoji": "🗺️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.culturalHeritagePreservation",
            "path": "/frameworks/cultural-heritage-preservation",
            "status": "planned",
            "emoji": "🏛️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.digitalCommons",
            "path": "/frameworks/digital-commons",
            "status": "review",
            "emoji": "💻"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.religiousAndSpiritualDialogueGovernance",
            "path": "/frameworks/religious-and-spiritual-dialogue-governance",
            "status": "review",
            "emoji": "🕯️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.globalCitizenshipPractice",
            "path": "/frameworks/global-citizenship-practice",
            "status": "review",
            "emoji": "🤝"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.artsFlourishing",
            "path": "/frameworks/arts-flourishing",
            "status": "planned",
            "emoji": "🎨"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.bioregionalPolis",
            "path": "/frameworks/bioregional-polis",
            "status": "coming-soon",
            "emoji": "🏙️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.livingLandProtocol",
            "path": "/frameworks/living-land-protocol",
            "status": "planned",
            "emoji": "🛖"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.regenerativeJourneys",
            "path": "/frameworks/regenerative-journeys",
            "status": "ready",
            "emoji": "👣"
          }
        ]
      },
      {
        "titleKey": "framework.tier.4.title",
        "path": "/frameworks/tier-4",
        "subItems": [
          {
            "titleKey": "framework.docs.nav.frameworkTitles.consciousnessAndInnerDevelopment",
            "path": "/frameworks/consciousness-and-inner-development",
            "status": "review",
            "emoji": "🧘"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.wiseDecisionMakingProtocol",
            "path": "/frameworks/wise-decision-making-protocol",
            "status": "review",
            "emoji": "🧭"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.existentialRiskGovernance",
            "path": "/frameworks/existential-risk-governance",
            "status": "planned",
            "emoji": "⚠️"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.spaceGovernance",
            "path": "/frameworks/space-governance",
            "status": "planned",
            "emoji": "🚀"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.millenniumProtocol",
            "path": "/frameworks/millennium-protocol",
            "status": "planned",
            "version": "6.0",
            "emoji": "🌌"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.deepTimeGovernance",
            "path": "/frameworks/deep-time-governance",
            "status": "planned",
            "emoji": "⏳"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.wisdomGovernance",
            "path": "/frameworks/wisdom-governance",
            "status": "planned",
            "emoji": "🦉"
          },
          {
            "titleKey": "framework.docs.nav.frameworkTitles.oracleProtocol",
            "path": "/frameworks/oracle-protocol",
            "status": "planned",
            "version": "2.7",
            "emoji": "🔮"
          }
        ]
      }
    ]
  },
  {
    "titleKey": "framework.docs.nav.guides",
    "path": "/frameworks/guides"
  },
  {
    "titleKey": "framework.docs.nav.regionalHubs",
    "path": "/frameworks/hubs"
  },
  {
    "titleKey": "framework.docs.nav.implementationTools",
    "path": "/frameworks/tools"
  },
  {
    "titleKey": "framework.docs.nav.visualizations",
    "path": "/frameworks/visuals"
  },
  {
    "titleKey": "framework.docs.nav.downloads",
    "path": "/downloads"
  },
  {
    "titleKey": "framework.docs.nav.caseStudies",
    "path": "/frameworks/docs/case-studies"
  },
  {
    "titleKey": "framework.docs.nav.aiFutures",
    "path": "/frameworks/ai-futures"
  },
  {
    "titleKey": "framework.docs.nav.resources",
    "path": "/frameworks/docs/resources"
  },
  {
    "titleKey": "framework.docs.nav.glossary",
    "path": "/frameworks/docs/glossary"
  }
];
  return navStructure;
}

// Create a writable store with the built navigation structure
export const frameworkNav = writable(buildNavStructure(allFrameworks));

// Existing update functions (maintained for backwards compatibility)
export function updateNavItem(titleKey, newData) {
  frameworkNav.update(nav => {
    return nav.map(item => {
      if (item.titleKey === titleKey) {
        return { ...item, ...newData };
      }
      return item;
    });
  });
}

export function updateFrameworkVersion(path, version) {
  // Update in master list
  const frameworkIndex = allFrameworks.findIndex(f => f.path === path);
  if (frameworkIndex !== -1) {
    allFrameworks[frameworkIndex].version = version;
  }
  
  // Update in nav store
  frameworkNav.update(nav => {
    return updateItemVersion(nav, path, version);
  });
}

// Recursive function to find and update version in nested structure
function updateItemVersion(items, targetPath, version) {
  return items.map(item => {
    if (item.path === targetPath) {
      return { ...item, version };
    }
    if (item.subItems) {
      return {
        ...item,
        subItems: updateItemVersion(item.subItems, targetPath, version)
      };
    }
    return item;
  });
}

// SCHEMA INTEGRATION NOTICE:
// This file is now generated from the GGF Master Schema.
// The schema serves as the single source of truth for:
// - Framework names, descriptions, and metadata
// - Implementation tiers and dependencies  
// - UI routing and internationalization keys
// - Status tracking and version management
//
// To add a new framework:
// 1. Add it to the appropriate cluster file in /src/lib/data/schema/
// 2. Include ui metadata for navigation generation
// 3. Run: npm run generate:nav
//
// The navigation will be automatically updated with correct dependencies,
// tier placement, and routing information.
